services:
  db:
    image: postgres:16
    container_name: apply_track_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apply_track
    ports:
      - "5432:5432"
    volumes:
      - apply_track_data:/var/lib/postgresql/data

volumes:
  apply_track_data:
